[tox]
envlist = py{310,311,312,313,314}, pre-commit
requires = tox-uv

[testenv]
runner = uv-venv-lock-runner
commands = python -m unittest discover -v

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files
